- debug: var=servers

- lineinfile:
    dest: /etc/hosts
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items: servers

- yum: name={{ item }}
  with_items:
  - /vagrant/vendor/jre-8u65-linux-x64.rpm

- yum: pkg={{ item }} state=latest
  with_items:
  - vim
  - wget
  - telnet
  - nmap-ncat
  - epel-release

- yum: pkg={{ item }} state=latest
  with_items:
  - jna

# - copy:
#     content: |
#       [datastax]
#       name = DataStax Repo for Apache Cassandra
#       baseurl = http://rpm.datastax.com/community
#       enabled = 1
#       gpgcheck = 0
#     dest: /etc/yum.repos.d/datastax.repo
# - yum: pkg={{ item }} state=latest
#   with_items:
#   - dsc21
#   - cassandra21
#   - cassandra21-tools

- unarchive:
    src: /vagrant/vendor/apache-cassandra-{{cassandra_version}}-bin.tar.gz
    dest: /opt
    copy: no
    creates: /opt/apache-cassandra-{{cassandra_version}}

- file:
    path: /opt/apache-cassandra-{{cassandra_version}}
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant

- template:
    src: cassandra-{{cassandra_version}}.yaml.j2
    dest: /opt/apache-cassandra-{{cassandra_version}}/conf/cassandra.yaml
    owner: vagrant
    group: vagrant

- file:
    dest: /opt/apache-cassandra-{{cassandra_version}}/logs
    state: directory
    owner: vagrant
    group: vagrant

- copy:
    content: |
      #!/bin/bash
      /opt/apache-cassandra-{{cassandra_version}}/bin/cassandra > /opt/apache-cassandra-{{cassandra_version}}/logs/cassandra.log
    dest: /home/vagrant/cassandra-start.sh
    mode: u+x
    owner: vagrant
    group: vagrant

- copy:
    content: |
      #!/bin/bash
      /opt/apache-cassandra-{{cassandra_version}}/bin/nodetool status
    dest: /home/vagrant/cassandra-status.sh
    mode: u+x
    owner: vagrant
    group: vagrant

- file:
    src: /opt/apache-cassandra-{{cassandra_version}}/logs/cassandra.log
    dest: /home/vagrant/cassandra.log
    force: yes
    state: link
    owner: vagrant
    group: vagrant

- lineinfile:
    dest: /home/vagrant/.bashrc
    line: "export PATH=/opt/apache-cassandra-{{cassandra_version}}/bin:$PATH"
